# Site settings
author: Elizabeth Karst
title: Karst Code
header-img: img/home-bg.png
email: efkarst@outlook.com
copyright_name: Elizabeth Karst
description: > # this means to ignore newlines until "baseurl:"
  From Product Manager to Full Stack Developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  efkarst

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
